myapps/adopcion/urls.py
from django.conf.urls import url

from myapps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^$', index_adopcion),
    url(r'^solicitud/listar$',SolicitudList.as_view(), name="solicitud_listar"),
    url(r'^solicitud/crear$',SolicitudCreate.as_view(), name="solicitud_crear"),
    url(r'^solicitud/editar/(?P<pk>\d+)$',SolicitudUpdate.as_view(), name="solicitud_editar"),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$',SolicitudDelete.as_view(), name="solicitud_eliminar"),
]

myapps/mascota/urls.py
from django.conf.urls import url

from myapps.mascota.views import listado, index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'^nuevo$', mascota_view, name='mascota_crear'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    # url(r'^listar$', mascota_list, name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    # url(r'^editar/(?P<id_mascota>\d+)/$', mascota_edit, name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    # url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name='mascota_eliminar'),
    url(r'^listado$', listado, name="listado"),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('myapps.mascota.urls',namespace="mascota")),
    url(r'^adopcion/', include ('myapps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include ('myapps.usuario.urls',namespace="usuario")),
    url(r'^accounts/login/', login,{'template_name':'index.html'},name="login"),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset$', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done$', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done$', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    ]

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->

		<title>{% block title %} Document {% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
		{% block extrahead%}
		{% endblock %}

	</head>
	<body>
		
		{% block header%}
		<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="dropdownMenu1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Mascotas
				</a>
				<div class="dropdown">
					<div class="dropdown-menu" aria-labelledby="dropdownMenu1">
						<a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar</a>
						<a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Crear</a>
					</div>
				</div>
      </li>
      <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdownMenu2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Adopciones
					</a>
				<div class="dropdown">
					<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
						<a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Listar</a>
						<a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Crear</a>
					</div>
				</div>
      </li>
      
		</ul>
		
		<ul class="navbar-nav">
				<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="dropdownMenu2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Opciones
						</a>
					<div class="dropdown">
						<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
							<a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
						</div>
					</div>
				</li>
		</ul>
    
  </div>
</nav>
		{% endblock%}

		{% block content %}
			<main>
				<div class="container">
					block main
				</div>
			</main>
		{% endblock %}

		{% block footer %}
		<footer class="bg-success">
			<div class="container">
				<p class="text-center">Todos los derechos reservados</p>
			</div>
		</footer>
		{% endblock%}

		{% block extrajs %}
		{% endblock %}
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		
	</body>
</html>